dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
memory_extraction_skill:
  type: str
  option: true
memory_storage_capacity:
  type: str
  option: true
storm_endurance:
  type: str
  option: true
black_market_contact_level:
  type: str
  option: true
