dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
memory_balance:
  type: str
  option: true
credit_grade:
  type: str
  option: true
class_color_badge:
  type: str
  option: true
district_level:
  type: str
  option: true
has_secret_vault:
  type: str
  option: true
