dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
extracted_memory_types:
  type: str
  option: true
remaining_memory_volume:
  type: str
  option: true
vault_memory_count:
  type: str
  option: true
forgotten_event_count:
  type: str
  option: true
