dim_name: PersonalityDim
traits:
  type: list_str
values:
  type: list_str
speech_style:
  type: str
attitude_towards_memory_trade:
  type: str
  option: true
memory_addiction_level:
  type: str
  option: true
risk_preference:
  type: str
  option: true
trust_in_others:
  type: str
  option: true
