dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
is_secret_passage:
  type: str
  option: true
current_control_faction:
  type: str
  option: true
has_portrait_guardian:
  type: str
  option: true
magical_enhancements:
  type: str
  option: true
historical_significance:
  type: str
  option: true
