dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
entry_min_memory_quota:
  type: str
  option: true
interior_security_level:
  type: str
  option: true
visitor_policy_type:
  type: str
  option: true
memory_detection_system:
  type: str
  option: true
clearance_override_protocol:
  type: str
  option: true
biometric_scan_requirements:
  type: str
  option: true
