dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
password_required:
  type: str
  option: true
countercurse_required:
  type: str
  option: true
invisibility_required:
  type: str
  option: true
anti_disapparition:
  type: str
  option: true
patrolled_by_filch:
  type: str
  option: true
monitored_by_carrows:
  type: str
  option: true
blocked_by_dark_magic:
  type: str
  option: true
alternative_route_available:
  type: str
  option: true
