dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
from_room_security_level:
  type: str
  option: true
to_room_security_level:
  type: str
  option: true
start_has_hidden_entrance:
  type: str
  option: true
end_has_hidden_entrance:
  type: str
  option: true
time_restriction:
  type: str
  option: true
is_one_way:
  type: str
  option: true
magical_interference:
  type: str
  option: true
