dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
alias:
  type: str
  option: true
magical_signature:
  type: str
  option: true
is_secret:
  type: str
  option: true
is_known_to_death_eaters:
  type: str
  option: true
requires_passphrase:
  type: str
  option: true
inventory_item_required:
  type: str
  option: true
