dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
memory_reserve_level:
  type: str
  option: true
operational_status:
  type: str
  option: true
structural_integrity:
  type: str
  option: true
emergency_protocol_active:
  type: str
  option: true
occupation_ratio:
  type: str
  option: true
last_memory_audit_date:
  type: str
  option: true
