dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
memory_asset_balance:
  type: str
  option: true
memory_debt_amount:
  type: str
  option: true
debt_repayment_status:
  type: str
  option: true
identity_archive_number:
  type: str
  option: true
social_credit_grade:
  type: str
  option: true
memory_status_code:
  type: str
  option: true
identity_qualification_flag:
  type: str
  option: true
stance_towards_memory_bureau:
  type: str
  option: true
