dim_name: StateDim
location:
  location_id:
    type: str
    ref: location
position:
  x:
    type: float
  y:
    type: float
current_memory_debt_status:
  type: str
  option: true
memory_supply_in_body:
  type: str
  option: true
identity_integrity_level:
  type: str
  option: true
debt_labor_remaining_hours:
  type: str
  option: true
storm_shelter_proximity:
  type: str
  option: true
archive_watchlist_flag:
  type: str
  option: true
black_market_connection_level:
  type: str
  option: true
resistance_network_contact_status:
  type: str
  option: true
