dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
energy_shield_level:
  type: str
  option: true
storm_noise_index:
  type: str
  option: true
memory_traffic_volume:
  type: str
  option: true
passage_security_level:
  type: str
  option: true
