dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
credit_threshold:
  type: str
  option: true
requires_id_card:
  type: str
  option: true
storm_protocol_active:
  type: str
  option: true
memory_device_allowed:
  type: str
  option: true
toll_cost_memories:
  type: str
  option: true
curfew_restricted:
  type: str
  option: true
