dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
path_type:
  type: str
  option: true
is_official:
  type: str
  option: true
is_monitored:
  type: str
  option: true
maintenance_status:
  type: str
  option: true
is_restricted:
  type: str
  option: true
is_secret:
  type: str
  option: true
