dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
storm_threat_index:
  type: str
  option: true
airtight_integrity_rating:
  type: str
  option: true
memory_toll_cost:
  type: str
  option: true
surveillance_scan_frequency:
  type: str
  option: true
operating_hours:
  type: str
  option: true
memory_storage_device_permission:
  type: str
  option: true
credential_level_required:
  type: str
  option: true
emergency_seal_status:
  type: str
  option: true
