dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
pressure_differential:
  type: str
  option: true
transit_time_minutes:
  type: str
  option: true
endpoint_security_checkpoints:
  type: str
  option: true
memory_gateway_type:
  type: str
  option: true
endpoint_jurisdiction:
  type: str
  option: true
track_connection_type:
  type: str
  option: true
