dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
route_number:
  type: str
  option: true
historical_memory_value:
  type: str
  option: true
administrative_district:
  type: str
  option: true
traffic_purpose:
  type: str
  option: true
encryption_level:
  type: str
  option: true
monopoly_authority:
  type: str
  option: true
