dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
description:
  type: str
magical_signature:
  type: str
  option: true
historical_importance:
  type: str
  option: true
house_affiliation:
  type: str
  option: true
hidden_bounds:
  type: str
  option: true
