dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
traversal_time:
  type: str
  option: true
spatial_layer:
  type: str
  option: true
requires_teleport:
  type: bool
  option: true
waypoint_names:
  type: list_str
  option: true
