dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
storm_protection_rating:
  type: str
  option: true
infrastructure_integrity:
  type: str
  option: true
stored_memory_volume:
  type: str
  option: true
energy_supply_status:
  type: str
  option: true
occupancy_density:
  type: str
  option: true
