dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
required_tribe_document:
  type: str
  option: true
plant_scan_required:
  type: str
  option: true
allowed_operating_hours:
  type: str
  option: true
armed_escort_mandatory:
  type: str
  option: true
contamination_level_threshold:
  type: str
  option: true
diplomatic_status_penalty:
  type: str
  option: true
