dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
from_tribe_control:
  type: str
  option: true
to_tribe_control:
  type: str
  option: true
from_plant_activity_index:
  type: str
  option: true
to_plant_activity_index:
  type: str
  option: true
from_resource_richness:
  type: str
  option: true
to_resource_richness:
  type: str
  option: true
