dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
memory_toll_required:
  type: str
  option: true
credit_rating_threshold:
  type: str
  option: true
storm_alert_restriction:
  type: str
  option: true
emergency_protocol_level:
  type: str
  option: true
inspection_requirements:
  type: str
  option: true
black_market_access_flag:
  type: str
  option: true
