dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
checkpoint_count:
  type: str
  option: true
security_sweep_frequency:
  type: str
  option: true
traffic_capacity:
  type: str
  option: true
alternate_route_links:
  type: str
  option: true
memory_flow_pipeline:
  type: str
  option: true
vulnerability_to_sabotage:
  type: str
  option: true
