dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
storm_exposure_level:
  type: str
  option: true
construction_material:
  type: str
  option: true
maintenance_status:
  type: str
  option: true
historical_significance:
  type: str
  option: true
covert_route_flag:
  type: str
  option: true
