dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
target_memory_to_restore:
  type: str
  option: true
desired_memory_assets:
  type: str
  option: true
memory_debt_clearance_goal:
  type: str
  option: true
planned_resistance_action:
  type: str
  option: true
archival_access_objective:
  type: str
  option: true
storm_window_exploitation_plan:
  type: str
  option: true
