dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
primary_magic_discipline:
  type: str
  option: true
combat_role:
  type: str
  option: true
dark_arts_proficiency:
  type: str
  option: true
defensive_magic_proficiency:
  type: str
  option: true
occlumency_proficiency:
  type: str
  option: true
animagus_form:
  type: str
  option: true
