dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
war_objective:
  type: str
  option: true
personal_quest:
  type: str
  option: true
survival_priority:
  type: str
  option: true
loyalty_goal:
  type: str
  option: true
power_ambition:
  type: str
  option: true
