dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
house:
  type: str
  option: true
blood_status:
  type: str
  option: true
faction_alignment:
  type: str
  option: true
secret_loyalty:
  type: str
  option: true
dark_mark_branded:
  type: str
  option: true
affiliation_conflict:
  type: str
  option: true
