dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
personal_ambition:
  type: str
  option: true
tribe_objective:
  type: str
  option: true
plant_research_goal:
  type: str
  option: true
exploration_target:
  type: str
  option: true
