dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
subway_line:
  type: str
  option: true
tribe_position:
  type: str
  option: true
origin_zone:
  type: str
  option: true
special_title:
  type: str
  option: true
