dim_name: StateDim
location:
  location_id:
    type: str
    ref: location
position:
  x:
    type: float
  y:
    type: float
current_line:
  type: str
  option: true
hunger_level:
  type: str
  option: true
plant_exposure_level:
  type: str
  option: true
is_isolated:
  type: str
  option: true
