dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
storm_emergency_access:
  type: str
  option: true
memory_tax_exempt:
  type: bool
  option: true
required_memory_clearance:
  type: int
  option: true
secret_access_available:
  type: bool
  option: true
