dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
importance:
  type: str
description:
  type: str
memory_function:
  type: str
  option: true
social_stratum:
  type: str
  option: true
institutional_affiliation:
  type: str
  option: true
unique_memory_resource:
  type: str
  option: true
