dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
structural_integrity:
  type: float
  option: true
storm_exposure:
  type: str
  option: true
memory_reserve_volume:
  type: int
  option: true
energy_status:
  type: str
  option: true
operational_status:
  type: str
  option: true
