agents:
  - name: StoryAgent
    component_order:
      - perceive
      - plan
      - invoke
      - state
      - reflect
    components:
      perceive:
        plugin: BasicPerceivePlugin
        module: examples.story.plugins.agent.perceive.BasicPerceivePlugin
      plan:
        plugin: BasicPlanPlugin
        module: examples.story.plugins.agent.plan.BasicPlanPlugin
      invoke:
        plugin: BasicInvokePlugin
        module: examples.story.plugins.agent.invoke.BasicInvokePlugin
        adapters:
          redis: RedisKVAdapter
      state:
        plugin: BasicStatePlugin
        module: examples.story.plugins.agent.state.BasicStatePlugin
        adapters:
          redis: RedisKVAdapter
      reflect:
        plugin: BasicReflectPlugin
        module: examples.story.plugins.agent.reflect.BasicReflectPlugin
