simulation:
  max_ticks: 120   # 10天 × 12tick/天

api_server:
  host: "0.0.0.0"
  port: 8001        # 与deduction区分，使用8001端口

pod:
  pod_size: 5

agent_template: "StoryAgent"

db: !include db_config.yaml
system: !include system_config.yaml
agents: !include agents_config.yaml
actions: !include actions_config.yaml
environment: !include environment_config.yaml
