name: WorldKernelEnvironment
components:
  relation:
    plugin:
      BasicRelationPlugin:
        relations: agents_relation
  space:
    plugin:
      BasicSpacePlugin:
        locations: map_locations
