dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
time_restrictions:
  type: str
  option: true
gender_restriction:
  type: str
  option: true
special_event_rules:
  type: str
  option: true
maintenance_state:
  type: str
  option: true
traffic_volume:
  type: str
  option: true
