dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
is_public:
  type: str
  option: true
length_steps:
  type: str
  option: true
barriers:
  type: str
  option: true
guards:
  type: str
  option: true
seasonal_use:
  type: str
  option: true
direction:
  type: str
  option: true
visibility:
  type: str
  option: true
