dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
surveillance_level:
  type: str
  option: true
magical_barrier:
  type: str
  option: true
barrier_type:
  type: str
  option: true
disillusionment_charm:
  type: str
  option: true
password_required:
  type: str
  option: true
evasion_methods:
  type: str
  option: true
