dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
description:
  type: str
castle_area:
  type: str
  option: true
security_level:
  type: str
  option: true
resident_characters:
  type: str
  option: true
availability_to_students:
  type: str
  option: true
hidden_elements:
  type: str
  option: true
is_variable_space:
  type: str
  option: true
switch_condition:
  type: str
  option: true
