dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
state_description:
  type: str
  option: true
state_switch_possible:
  type: str
  option: true
state_switch_condition:
  type: str
  option: true
maintenance_level:
  type: str
  option: true
occupied_by_death_eaters:
  type: str
  option: true
