dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
memory_appraisal_precision:
  type: str
  option: true
negotiation_power:
  type: int
  option: true
storm_survival_training:
  type: str
  option: true
memory_clearance_level:
  type: str
  option: true
illegal_tech_familiarity:
  type: str
  option: true
