dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
social_class:
  type: str
  option: true
faction_affiliation:
  type: str
  option: true
wanted_level:
  type: str
  option: true
memory_reputation_index:
  type: float
  option: true
