dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
memory_credit:
  type: str
  option: true
social_class:
  type: str
  option: true
faction_affiliation:
  type: str
  option: true
