dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
memory_quality:
  type: str
  option: true
memory_emotion_value:
  type: str
  option: true
memory_vault_level:
  type: str
  option: true
