dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
memory_appraisal_skill:
  type: str
  option: true
memory_manipulation_resistance:
  type: str
  option: true
storm_tolerance_threshold:
  type: str
  option: true
anchor_verification_proficiency:
  type: str
  option: true
blackmail_protocol_knowledge:
  type: str
  option: true
