dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
identity_anchor_code:
  type: str
  option: true
memory_asset_level:
  type: str
  option: true
legal_status:
  type: str
  option: true
civic_rank:
  type: str
  option: true
registry_identification:
  type: str
  option: true
