dim_name: PersonalityDim
traits:
  type: list_str
values:
  type: list_str
speech_style:
  type: str
attitude_toward_memory_trade:
  type: str
  option: true
risk_tolerance:
  type: str
  option: true
nostalgia_bias:
  type: str
  option: true
suspicion_index:
  type: str
  option: true
reaction_to_identity_threats:
  type: str
  option: true
