dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
description:
  type: str
belongs_to_zone:
  type: str
  option: true
architectural_style:
  type: str
  option: true
prominence_rank:
  type: str
  option: true
primary_function:
  type: str
  option: true
owner_or_occupant:
  type: str
  option: true
