dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
description:
  type: str
energy_shield_level:
  type: str
  option: true
memory_storage_density:
  type: str
  option: true
storm_noise_index:
  type: str
  option: true
is_trading_allowed:
  type: str
  option: true
