dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
energy_shield_percentage:
  type: str
  option: true
current_occupancy:
  type: str
  option: true
storm_alert_level:
  type: str
  option: true
last_maintenance_time:
  type: str
  option: true
