dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
age:
  type: str
  option: true
generation:
  type: str
  option: true
gender:
  type: str
  option: true
rank:
  type: str
  option: true
relationship_to_jia:
  type: str
  option: true
residence:
  type: str
  option: true
fate_hint:
  type: str
  option: true
