dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
childhood_experience:
  type: str
  option: true
important_impressions:
  type: str
  option: true
hidden_memories:
  type: str
  option: true
