dim_name: StateDim
location:
  location_id:
    type: str
    ref: location
position:
  x:
    type: float
  y:
    type: float
current_activity:
  type: str
  option: true
health_status:
  type: str
  option: true
mood:
  type: str
  option: true
