dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
economic_status:
  type: str
  option: true
repair_condition:
  type: str
  option: true
current_activity:
  type: str
  option: true
occupancy:
  type: str
  option: true
security_level:
  type: str
  option: true
