dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
memory_debt_repayment_target:
  type: str
  option: true
desired_identity_credit_rank:
  type: str
  option: true
planned_memory_retention_priority:
  type: str
  option: true
ambition_to_access_upper_deck:
  type: str
  option: true
goal_to_preserve_critical_private_memories:
  type: str
  option: true
