dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
memory_credit_balance:
  type: str
  option: true
memory_archive_id:
  type: str
  option: true
identity_credit_level:
  type: str
  option: true
assigned_district:
  type: str
  option: true
institution_affiliation:
  type: str
  option: true
resistance_affiliation:
  type: str
  option: true
