dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
memories_recently_sold_or_seized:
  type: str
  option: true
hidden_memory_backups_locations:
  type: str
  option: true
knowledge_of_illegal_memory_routes:
  type: str
  option: true
records_of_storm_tax_evasion:
  type: str
  option: true
personal_experiences_of_memory_revaluation:
  type: str
  option: true
forgotten_memory_gaps_from_forced_extraction:
  type: str
  option: true
