dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
memory_credit_rating:
  type: str
  option: true
known_as_memory_debtor:
  type: str
  option: true
archival_access_permission_label:
  type: str
  option: true
black_market_contact_status:
  type: str
  option: true
voting_rights_status_in_storm_council:
  type: str
  option: true
