dim_name: StateDim
location:
  location_id:
    type: str
    ref: location
position:
  x:
    type: float
  y:
    type: float
current_storm_warning_level:
  type: str
  option: true
memory_access_terminal_proximity:
  type: str
  option: true
creditor_presence_nearby:
  type: str
  option: true
surveillance_drone_overhead_status:
  type: str
  option: true
shelter_occupancy_status:
  type: str
  option: true
