dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
storm_stability_index:
  type: str
  option: true
memory_contamination_risk:
  type: str
  option: true
required_pressure_gear:
  type: str
  option: true
temporary_pass_allowed:
  type: str
  option: true
evacuation_priority_score:
  type: str
  option: true
