dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
path_name_display:
  type: str
  option: true
path_subtype:
  type: str
  option: true
storm_seal_rating:
  type: str
  option: true
memory_purity_filter_capability:
  type: str
  option: true
surveillance_level:
  type: str
  option: true
