dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
minimum_memory_asset_credit:
  type: str
  option: true
security_clearance_level:
  type: str
  option: true
storm_alert_access_status:
  type: str
  option: true
required_identity_certification:
  type: str
  option: true
debt_labor_pass_requirement:
  type: str
  option: true
