dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
description:
  type: str
memory_archive_sector_code:
  type: str
  option: true
facility_function_type:
  type: str
  option: true
administrative_district:
  type: str
  option: true
historical_memory_event_id:
  type: str
  option: true
storm_exposure_zone:
  type: str
  option: true
