dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
transit_time_minutes:
  type: float
  option: true
elevation_change:
  type: float
  option: true
security_gradient:
  type: str
  option: true
connection_type:
  type: str
  option: true
carries_live_memory:
  type: bool
  option: true
