dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
route_code:
  type: str
  option: true
architecture_style:
  type: str
  option: true
visual_ambience:
  type: str
  option: true
traffic_priority:
  type: str
  option: true
memory_role:
  type: str
  option: true
