dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
entry_token:
  type: str
  option: true
guardians:
  type: str
  option: true
restriction_level:
  type: int
  option: true
alignment_requirement:
  type: str
  option: true
