dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
spiritual_energy:
  type: str
  option: true
current_event:
  type: str
  option: true
celestial_weather:
  type: str
  option: true
danger_level:
  type: int
  option: true
