dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
domestic_management_skill:
  type: str
  option: true
literary_skill:
  type: str
  option: true
financial_acuity:
  type: str
  option: true
ritual_knowledge:
  type: str
  option: true
