dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
generation:
  type: str
  option: true
status:
  type: str
  option: true
economic_role:
  type: str
  option: true
servant_grade:
  type: str
  option: true
lineage:
  type: str
  option: true
