dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
family_history_knowledge:
  type: str
  option: true
scandal_knowledge:
  type: str
  option: true
love_affair_secret:
  type: str
  option: true
