dim_name: PersonalityDim
traits:
  type: list_str
values:
  type: list_str
speech_style:
  type: str
filial_piety_level:
  type: str
  option: true
ambition:
  type: str
  option: true
conservativeness:
  type: str
  option: true
emotion_expressiveness:
  type: str
  option: true
