dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
faction:
  type: str
  option: true
patron:
  type: str
  option: true
allies:
  type: str
  option: true
rivals:
  type: str
  option: true
