dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
requires_announcement:
  type: str
  option: true
time_access:
  type: str
  option: true
requires_token:
  type: str
  option: true
requires_maid_accompany:
  type: str
  option: true
has_night_watch:
  type: str
  option: true
weather_affected:
  type: str
  option: true
lighting:
  type: str
  option: true
