dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
has_gate_type:
  type: str
  option: true
has_steps:
  type: str
  option: true
has_screen_wall:
  type: str
  option: true
allows_palanquin:
  type: str
  option: true
gender_restriction:
  type: str
  option: true
