dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
social_circle_tags:
  type: str
  option: true
intimate_coterie:
  type: str
  option: true
faction_alignment:
  type: str
  option: true
gossip_status:
  type: str
  option: true
matriarchal_favor:
  type: str
  option: true
peer_regard:
  type: str
  option: true
servant_relationship:
  type: str
  option: true
external_connection:
  type: str
  option: true
marriage_prospect_rank:
  type: str
  option: true
