dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
magic_treasures:
  type: list_str
  option: true
combat_rating:
  type: str
  option: true
ability_origin:
  type: str
  option: true
