dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
war_deeds:
  type: list_str
  option: true
known_secrets:
  type: list_str
  option: true
offense_history:
  type: list_str
  option: true
