dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
terminal_gate_type:
  type: str
  option: true
traffic_control_point:
  type: str
  option: true
connection_mode:
  type: str
  option: true
memory_transfer_capacity:
  type: str
  option: true
emergency_bypass_route:
  type: str
  option: true
port_security_level:
  type: str
  option: true
