dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
description:
  type: str
subway_line_affiliation:
  type: str
  option: true
plant_control_degree:
  type: str
  option: true
resource_richness:
  type: str
  option: true
historical_significance:
  type: str
  option: true
tribe_occupation_status:
  type: str
  option: true
