dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
occlumency_level:
  type: str
  option: true
legilimency_level:
  type: str
  option: true
specialized_magic:
  type: str
  option: true
wand_core:
  type: str
  option: true
animagus_form:
  type: str
  option: true
