dim_name: PersonalityDim
traits:
  type: list_str
values:
  type: list_str
speech_style:
  type: str
fear_level:
  type: str
  option: true
defiance_level:
  type: str
  option: true
moral_grey_degree:
  type: str
  option: true
paranoia_index:
  type: str
  option: true
