dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
faction:
  type: str
  option: true
resistance_network_member:
  type: str
  option: true
trustworthiness_score:
  type: str
  option: true
