dim_name: StateDim
location:
  location_id:
    type: str
    ref: location
position:
  x:
    type: float
  y:
    type: float
hidden_status:
  type: str
  option: true
safety_level:
  type: str
  option: true
last_seen_location:
  type: str
  option: true
disguise_active:
  type: str
  option: true
